# Generated by Django 4.0.4 on 2022-05-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ('start_date',)},
        ),
    ]
