# Generated by Django 4.0.4 on 2022-05-23 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
